# Generated by Django 4.1.5 on 2023-01-26 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('k2app', '0002_cars'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cars',
            new_name='Car',
        ),
    ]
