# Generated by Django 4.1.5 on 2023-02-16 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k2app', '0005_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.FloatField(default=0),
        ),
    ]
