# Generated by Django 4.1.5 on 2023-02-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k2app', '0006_car_seats_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
