# Generated by Django 4.1.5 on 2023-02-16 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('k2app', '0007_alter_car_seats_alter_car_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Top_Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deals', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='k2app.car')),
            ],
        ),
    ]
