# Generated by Django 4.1.5 on 2023-02-16 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('k2app', '0008_top_deals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Top_Deals',
            new_name='Top_Deal',
        ),
    ]
