# Generated by Django 4.1.5 on 2023-02-16 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('k2app', '0011_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
    ]
