# Generated by Django 4.1.5 on 2023-02-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('k2app', '0013_car_fuel_car_gearbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=12)),
                ('surname', models.CharField(default='', max_length=12)),
                ('email', models.EmailField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
                ('confirmpassword', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
